export interface WordItem {
  id: string;
  word: string;
  meaning: string;
  tag: string;
  pos?: string;
  status: "learning" | "memorized";
}

export const TOEIC_DUMMY_WORDS: WordItem[] = [
  { id: "d1", word: "accommodate", meaning: "수용하다, 편의를 도모하다", tag: "Part 7 빈출", pos: "동사", status: "learning" },
  { id: "d2", word: "implement", meaning: "실행하다, 이행하다", tag: "Part 5 빈출", pos: "동사", status: "learning" },
  { id: "d3", word: "subsequently", meaning: "그 후에, 나중에", tag: "Part 5 빈출", pos: "부사", status: "learning" },
  { id: "d4", word: "compliant", meaning: "순응하는, 규정을 준수하는", tag: "Part 7 빈출", pos: "형용사", status: "learning" },
  { id: "d5", word: "delegate", meaning: "위임하다, 대표", tag: "Part 5 빈출", pos: "동사/명사", status: "learning" },
  { id: "d6", word: "unprecedented", meaning: "전례 없는", tag: "Part 6 빈출", pos: "형용사", status: "learning" },
  { id: "d7", word: "mandatory", meaning: "의무적인, 필수의", tag: "Part 5 빈출", pos: "형용사", status: "learning" },
  { id: "d8", word: "lucrative", meaning: "수익성이 좋은", tag: "Part 7 빈출", pos: "형용사", status: "learning" },
  { id: "d9", word: "comprehensive", meaning: "포괄적인, 종합적인", tag: "Part 5 빈출", pos: "형용사", status: "learning" },
  { id: "d10", word: "fluctuate", meaning: "변동하다, 오르내리다", tag: "Part 6 빈출", pos: "동사", status: "learning" },
  { id: "d11", word: "tentative", meaning: "잠정적인, 임시의", tag: "Part 7 빈출", pos: "형용사", status: "learning" },
  { id: "d12", word: "obsolete", meaning: "구식의, 쓸모없어진", tag: "Part 5 빈출", pos: "형용사", status: "learning" },
  { id: "d13", word: "alleviate", meaning: "완화하다, 경감하다", tag: "Part 6 빈출", pos: "동사", status: "learning" },
  { id: "d14", word: "prominent", meaning: "저명한, 두드러진", tag: "Part 7 빈출", pos: "형용사", status: "learning" },
  { id: "d15", word: "scrutinize", meaning: "면밀히 조사하다", tag: "Part 5 빈출", pos: "동사", status: "learning" },
  { id: "d16", word: "consecutive", meaning: "연속적인", tag: "Part 5 빈출", pos: "형용사", status: "learning" },
  { id: "d17", word: "versatile", meaning: "다재다능한, 다용도의", tag: "Part 7 빈출", pos: "형용사", status: "learning" },
  { id: "d18", word: "incur", meaning: "(비용, 손실을) 초래하다, 발생시키다", tag: "Part 6 빈출", pos: "동사", status: "learning" },
  { id: "d19", word: "stringent", meaning: "엄격한", tag: "Part 5 빈출", pos: "형용사", status: "learning" },
  { id: "d20", word: "prospect", meaning: "전망, 예상", tag: "Part 7 빈출", pos: "명사", status: "learning" },
  { id: "d21", word: "initiative", meaning: "계획, 주도권", tag: "Part 5 빈출", pos: "명사", status: "learning" },
  { id: "d22", word: "exempt", meaning: "면제된", tag: "Part 6 빈출", pos: "형용사", status: "learning" },
  { id: "d23", word: "feasible", meaning: "실행 가능한", tag: "Part 7 빈출", pos: "형용사", status: "learning" },
  { id: "d24", word: "pertain", meaning: "속하다, 관련되다", tag: "Part 5 빈출", pos: "동사", status: "learning" },
  { id: "d25", word: "thorough", meaning: "철저한", tag: "Part 6 빈출", pos: "형용사", status: "learning" },
  { id: "d26", word: "supervise", meaning: "감독하다", tag: "Part 5 빈출", pos: "동사", status: "learning" },
  { id: "d27", word: "abundant", meaning: "풍부한", tag: "Part 7 빈출", pos: "형용사", status: "learning" },
  { id: "d28", word: "appraise", meaning: "평가하다", tag: "Part 5 빈출", pos: "동사", status: "learning" },
  { id: "d29", word: "commence", meaning: "시작하다", tag: "Part 6 빈출", pos: "동사", status: "learning" },
  { id: "d30", word: "dedicate", meaning: "헌신하다, 바치다", tag: "Part 5 빈출", pos: "동사", status: "learning" },
  { id: "d31", word: "endorse", meaning: "승인하다, 지지하다", tag: "Part 7 빈출", pos: "동사", status: "learning" },
  { id: "d32", word: "facilitate", meaning: "용이하게 하다", tag: "Part 5 빈출", pos: "동사", status: "learning" },
  { id: "d33", word: "hesitant", meaning: "주저하는", tag: "Part 6 빈출", pos: "형용사", status: "learning" },
  { id: "d34", word: "inquire", meaning: "문의하다", tag: "Part 5 빈출", pos: "동사", status: "learning" },
  { id: "d35", word: "jeopardize", meaning: "위태롭게 하다", tag: "Part 7 빈출", pos: "동사", status: "learning" },
  { id: "d36", word: "legitimate", meaning: "합법적인, 정당한", tag: "Part 5 빈출", pos: "형용사", status: "learning" },
  { id: "d37", word: "mutual", meaning: "상호간의", tag: "Part 6 빈출", pos: "형용사", status: "learning" },
  { id: "d38", word: "negotiate", meaning: "협상하다", tag: "Part 5 빈출", pos: "동사", status: "learning" },
  { id: "d39", word: "obligation", meaning: "의무", tag: "Part 7 빈출", pos: "명사", status: "learning" },
  { id: "d40", word: "perpetual", meaning: "영구적인", tag: "Part 5 빈출", pos: "형용사", status: "learning" },
  { id: "d41", word: "query", meaning: "질문, 문의", tag: "Part 6 빈출", pos: "명사", status: "learning" },
  { id: "d42", word: "reluctant", meaning: "꺼리는", tag: "Part 5 빈출", pos: "형용사", status: "learning" },
  { id: "d43", word: "substitute", meaning: "대체하다", tag: "Part 7 빈출", pos: "동사", status: "learning" },
  { id: "d44", word: "terminate", meaning: "끝내다, 종료하다", tag: "Part 5 빈출", pos: "동사", status: "learning" },
  { id: "d45", word: "unanimous", meaning: "만장일치의", tag: "Part 6 빈출", pos: "형용사", status: "learning" },
  { id: "d46", word: "validate", meaning: "입증하다, 승인하다", tag: "Part 5 빈출", pos: "동사", status: "learning" },
  { id: "d47", word: "warrant", meaning: "보증하다, 정당화하다", tag: "Part 7 빈출", pos: "동사", status: "learning" },
  { id: "d48", word: "yield", meaning: "생산하다, 양보하다", tag: "Part 5 빈출", pos: "동사", status: "learning" },
  { id: "d49", word: "zealous", meaning: "열성적인", tag: "Part 6 빈출", pos: "형용사", status: "learning" },
  { id: "d50", word: "adequate", meaning: "적절한, 충분한", tag: "Part 5 빈출", pos: "형용사", status: "learning" },
  { id: "d51", word: "beneficial", meaning: "유익한", tag: "Part 7 빈출", pos: "형용사", status: "learning" },
  { id: "d52", word: "capacity", meaning: "용량, 수용력", tag: "Part 5 빈출", pos: "명사", status: "learning" },
  { id: "d53", word: "derive", meaning: "끌어내다, 얻다", tag: "Part 6 빈출", pos: "동사", status: "learning" },
  { id: "d54", word: "evaluate", meaning: "평가하다", tag: "Part 5 빈출", pos: "동사", status: "learning" },
  { id: "d55", word: "fundamental", meaning: "근본적인, 핵심적인", tag: "Part 7 빈출", pos: "형용사", status: "learning" },
  { id: "d56", word: "generate", meaning: "발생시키다, 만들어내다", tag: "Part 5 빈출", pos: "동사", status: "learning" },
  { id: "d57", word: "highlight", meaning: "강조하다", tag: "Part 6 빈출", pos: "동사", status: "learning" },
  { id: "d58", word: "illustrate", meaning: "설명하다, 삽화를 넣다", tag: "Part 5 빈출", pos: "동사", status: "learning" },
  { id: "d59", word: "justify", meaning: "정당화하다", tag: "Part 7 빈출", pos: "동사", status: "learning" },
  { id: "d60", word: "knowledgeable", meaning: "아는 것이 많은, 정통한", tag: "Part 5 빈출", pos: "형용사", status: "learning" },
  { id: "d61", word: "logical", meaning: "논리적인", tag: "Part 6 빈출", pos: "형용사", status: "learning" },
  { id: "d62", word: "maintain", meaning: "유지하다", tag: "Part 5 빈출", pos: "동사", status: "learning" },
  { id: "d63", word: "notable", meaning: "주목할 만한, 유명한", tag: "Part 7 빈출", pos: "형용사", status: "learning" },
  { id: "d64", word: "objective", meaning: "객관적인, 목표", tag: "Part 5 빈출", pos: "형용사/명사", status: "learning" },
  { id: "d65", word: "participate", meaning: "참여하다", tag: "Part 6 빈출", pos: "동사", status: "learning" },
  { id: "d66", word: "qualify", meaning: "자격을 얻다", tag: "Part 5 빈출", pos: "동사", status: "learning" },
  { id: "d67", word: "recognize", meaning: "인정하다, 알아보다", tag: "Part 7 빈출", pos: "동사", status: "learning" },
  { id: "d68", word: "significant", meaning: "중요한, 상당한", tag: "Part 5 빈출", pos: "형용사", status: "learning" },
  { id: "d69", word: "transfer", meaning: "옮기다, 이체하다", tag: "Part 6 빈출", pos: "동사", status: "learning" },
  { id: "d70", word: "undergo", meaning: "겪다, 경험하다", tag: "Part 5 빈출", pos: "동사", status: "learning" },
  { id: "d71", word: "verify", meaning: "확인하다, 입증하다", tag: "Part 7 빈출", pos: "동사", status: "learning" },
  { id: "d72", word: "widespread", meaning: "광범위한", tag: "Part 5 빈출", pos: "형용사", status: "learning" },
  { id: "d73", word: "access", meaning: "접근, 접근하다", tag: "Part 6 빈출", pos: "명사/동사", status: "learning" },
  { id: "d74", word: "boost", meaning: "증대시키다, 촉진하다", tag: "Part 5 빈출", pos: "동사", status: "learning" },
  { id: "d75", word: "collaborate", meaning: "협력하다", tag: "Part 7 빈출", pos: "동사", status: "learning" },
  { id: "d76", word: "decline", meaning: "거절하다, 감소하다", tag: "Part 5 빈출", pos: "동사", status: "learning" },
  { id: "d77", word: "emerge", meaning: "나타나다, 부상하다", tag: "Part 6 빈출", pos: "동사", status: "learning" },
  { id: "d78", word: "forecast", meaning: "예측하다, 예보하다", tag: "Part 5 빈출", pos: "동사", status: "learning" },
  { id: "d79", word: "guarantee", meaning: "보장하다", tag: "Part 7 빈출", pos: "동사", status: "learning" },
  { id: "d80", word: "handle", meaning: "다루다, 처리하다", tag: "Part 5 빈출", pos: "동사", status: "learning" },
  { id: "d81", word: "incorporate", meaning: "포함하다, 통합하다", tag: "Part 6 빈출", pos: "동사", status: "learning" },
  { id: "d82", word: "journal", meaning: "전문지, 학술지", tag: "Part 5 빈출", pos: "명사", status: "learning" },
  { id: "d83", word: "keen", meaning: "열망하는, 예리한", tag: "Part 7 빈출", pos: "형용사", status: "learning" },
  { id: "d84", word: "launch", meaning: "시작하다, 출시하다", tag: "Part 5 빈출", pos: "동사", status: "learning" },
  { id: "d85", word: "modify", meaning: "수정하다", tag: "Part 6 빈출", pos: "동사", status: "learning" },
  { id: "d86", word: "navigate", meaning: "길을 찾다, 항해하다", tag: "Part 5 빈출", pos: "동사", status: "learning" },
  { id: "d87", word: "obtain", meaning: "얻다, 획득하다", tag: "Part 7 빈출", pos: "동사", status: "learning" },
  { id: "d88", word: "postpone", meaning: "연기하다", tag: "Part 5 빈출", pos: "동사", status: "learning" },
  { id: "d89", word: "quote", meaning: "견적을 내다, 인용하다", tag: "Part 6 빈출", pos: "동사", status: "learning" },
  { id: "d90", word: "resolve", meaning: "해결하다", tag: "Part 5 빈출", pos: "동사", status: "learning" },
  { id: "d91", word: "submit", meaning: "제출하다", tag: "Part 7 빈출", pos: "동사", status: "learning" },
  { id: "d92", word: "tackle", meaning: "다루다, 씨름하다", tag: "Part 5 빈출", pos: "동사", status: "learning" },
  { id: "d93", word: "update", meaning: "갱신하다", tag: "Part 6 빈출", pos: "동사", status: "learning" },
  { id: "d94", word: "vital", meaning: "필수적인, 생명에 관련된", tag: "Part 5 빈출", pos: "형용사", status: "learning" },
  { id: "d95", word: "withdraw", meaning: "철회하다, 인출하다", tag: "Part 7 빈출", pos: "동사", status: "learning" },
  { id: "d96", word: "accelerate", meaning: "가속화하다", tag: "Part 5 빈출", pos: "동사", status: "learning" },
  { id: "d97", word: "balance", meaning: "균형, 잔고", tag: "Part 6 빈출", pos: "명사", status: "learning" },
  { id: "d98", word: "calculate", meaning: "계산하다", tag: "Part 5 빈출", pos: "동사", status: "learning" },
  { id: "d99", word: "delay", meaning: "지연, 지연시키다", tag: "Part 7 빈출", pos: "명사/동사", status: "learning" },
  { id: "d100", word: "encourage", meaning: "격려하다, 권장하다", tag: "Part 5 빈출", pos: "동사", status: "learning" }
];
