-- 1. Create app_mode_enum
CREATE TYPE public.app_mode_enum AS ENUM ('teen', 'toeic');

-- 2. Add 'parent' to user_role ENUM
ALTER TYPE public.user_role ADD VALUE IF NOT EXISTS 'parent';

-- 3. Extend public.users table
ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS app_mode public.app_mode_enum,
  ADD COLUMN IF NOT EXISTS parent_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS class_id UUID REFERENCES public.classes(id) ON DELETE SET NULL;

-- 4. Extend public.classes table
-- Note: User requested to retain academy_id
ALTER TABLE public.classes
  ADD COLUMN IF NOT EXISTS teacher_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS class_code TEXT UNIQUE;

-- 5. Create public.cached_ai_responses table
CREATE TABLE IF NOT EXISTS public.cached_ai_responses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word_id TEXT NOT NULL,
    response_type TEXT NOT NULL,
    response_text JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
